### ISSUE TITLE
Release updated API to crates.io

### ISSUE THREAD

**Issue by brandonpollack23** [norse-rs/ash-window#5]
Hi It's me again!

I'm removing the git dependencies from my project and just noticed that the version on crates.io still uses required_device_extension instead of required_device_extentions

Was hoping you wouldn't mind pushing that to crates.io

**Comment by msiglreith** [comment]
Hi 👋 
sure, I published the latest master as 0.2.

**Comment by brandonpollack23** [comment]
Awesome thanks so much!
